dist: trusty
install: .travis/install
language: python
matrix:
  include:
  - language: generic
    os: osx
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
    dist: xenial
    sudo: true
  - python: "pypy3"
  - env: BUILD=sdist
    python: "3.6"
script: .travis/script
